apiVersion: v1
kind: Service
metadata:
  name: jstodo-41223-test-run1
  namespace: jstodo-41223-test-run1-ns
spec:
  type: LoadBalancer
  selector:
    app: jstodo-41223-test-run1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80